# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
# ForgeGradle 3/4 需 JDK8 运行守护进程
org.gradle.java.home=D:/tools/dragonwell-8
# Java toolchain 自动检测路径
org.gradle.java.installations.paths=D:/tools/dragonwell-8,D:/tools/dragonwell-17,D:/tools/dragonwell-25