plugins {
    id 'java'
    id 'gg.essential.loom' version '1.10.36'
}

version = '1.2.0'
group = 'org.soraworld.areaeffect'

base { archivesName = 'AreaEffect-1.9.4' }

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

loom {
    forge {
        pack200Provider.set(new dev.architectury.pack200.java.Pack200Adapter())
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://repo.essential.gg/repository/maven-public/' }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.9.4'
    mappings 'de.oceanlabs.mcp:mcp_stable:26-1.9.4'
    forge 'net.minecraftforge:forge:1.9.4-12.17.0.2317-1.9.4'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', '1.9.4'
    filesMatching('mcmod.info') {
        expand 'version': project.version, 'mcversion': '1.9.4'
    }
}