# 构建缓存与并行
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4G
# Loom 平台：Forge
loom.platform=forge
# 守护进程运行 JDK（Loom 依赖要求 Java 17+，此处用 JDK21）
org.gradle.java.home=D:/tools/dragonwell-21
# Java toolchain 自动检测路径（Java8 供编译 MC 使用）
org.gradle.java.installations.paths=D:/tools/dragonwell-8,D:/tools/dragonwell-17,D:/tools/dragonwell-21,D:/tools/dragonwell-25
