pluginManagement {
    repositories {
        maven {
            credentials {
                username = System.getenv('ALIYUN_MVN_USERNAME')
                password = System.getenv('ALIYUN_MVN_PASSWORD')
            }
            url = System.getenv('ALIYUN_MVN_URL')
        }
    }
}

rootProject.name = 'AreaEffect-1.7.10'
